<?php

namespace ContainerUjKk4fX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1uDCRvtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1uDCRvt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1uDCRvt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\BlogController::form' => ['privates', '.service_locator.VmyKyRl', 'get_ServiceLocator_VmyKyRlService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.ddtGBuI', 'get_ServiceLocator_DdtGBuIService', true],
            'App\\Controller\\BlogController::show' => ['privates', '.service_locator.zi5M3j.', 'get_ServiceLocator_Zi5M3j_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.Ah80EsV', 'get_ServiceLocator_Ah80EsVService', true],
            'App\\Controller\\BlogController:form' => ['privates', '.service_locator.VmyKyRl', 'get_ServiceLocator_VmyKyRlService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.ddtGBuI', 'get_ServiceLocator_DdtGBuIService', true],
            'App\\Controller\\BlogController:show' => ['privates', '.service_locator.zi5M3j.', 'get_ServiceLocator_Zi5M3j_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BlogController::delete' => '?',
            'App\\Controller\\BlogController::form' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BlogController:delete' => '?',
            'App\\Controller\\BlogController:form' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
