<?php

namespace ContainerBceres2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZIQxMrmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zIQxMrm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zIQxMrm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BlogController::deleteArticle' => ['privates', '.service_locator.L5e422z', 'get_ServiceLocator_L5e422zService', true],
            'App\\Controller\\BlogController::form' => ['privates', '.service_locator.YCe7BNT', 'get_ServiceLocator_YCe7BNTService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.aiQMjz2', 'get_ServiceLocator_AiQMjz2Service', true],
            'App\\Controller\\BlogController::show' => ['privates', '.service_locator.L5e422z', 'get_ServiceLocator_L5e422zService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\BlogController:deleteArticle' => ['privates', '.service_locator.L5e422z', 'get_ServiceLocator_L5e422zService', true],
            'App\\Controller\\BlogController:form' => ['privates', '.service_locator.YCe7BNT', 'get_ServiceLocator_YCe7BNTService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.aiQMjz2', 'get_ServiceLocator_AiQMjz2Service', true],
            'App\\Controller\\BlogController:show' => ['privates', '.service_locator.L5e422z', 'get_ServiceLocator_L5e422zService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\BlogController::deleteArticle' => '?',
            'App\\Controller\\BlogController::form' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BlogController:deleteArticle' => '?',
            'App\\Controller\\BlogController:form' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
