<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHDK7PFq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHDK7PFq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHDK7PFq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHDK7PFq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHDK7PFq\App_KernelDevDebugContainer([
    'container.build_hash' => 'HDK7PFq',
    'container.build_id' => '8bcea64e',
    'container.build_time' => 1649089875,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHDK7PFq');
