<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUjKk4fX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUjKk4fX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUjKk4fX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUjKk4fX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUjKk4fX\App_KernelDevDebugContainer([
    'container.build_hash' => 'UjKk4fX',
    'container.build_id' => '2d14f5c4',
    'container.build_time' => 1649065444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUjKk4fX');
